authapp/urls.py
"""
urls for authapp
"""

from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [

    path('login/', authapp.login_user, name='login'),

    path('logout/', authapp.logout, name='logout'),

    path('register/', authapp.register, name='register'),

    path('edit/', authapp.edit_user, name='edit'),

    path('delete-user/<int:pk>/', authapp.delete_user, name='delete_user'),

    path('ban-user/<int:pk>/<int:article>/', authapp.banned_user,
         name='ban_user'),

    path('edit-avatar/', authapp.edit_avatar, name='edit_avatar'),

    path('edit-password/', authapp.PasswordEditView.as_view(),
         name='edit_password'),
]

cabinetapp/urls.py
"""
urls for cabinetapp
"""

from django.urls import path

from .views import main, new_article, my_articles, delete_article, my_drafts, \
    edit_draft, moderation, moderation_check

app_name = "cabinetapp"

urlpatterns = [

    path('', main, name='cabinet'),

    path('new-article/', new_article, name='new_article'),

    path('my-articles/', my_articles, name='my_articles'),

    path('my-drafts/', my_drafts, name='my_drafts'),

    path('delete-article/<int:pk>/', delete_article, name='delete_article'),

    path('edit-draft/<int:pk>', edit_draft, name='edit_draft'),

    path('moderation/', moderation, name='moderation'),

    path('moderation_check/<int:pk>/<int:result>', moderation_check,
         name='moderation_check'),
]

knackbook/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [

    path('admin/', admin.site.urls, name='admin'),

    path('', include('mainapp.urls', namespace='main')),

    path('auth/', include('authapp.urls', namespace='auth')),

    path('comments/', include('commentapp.urls', namespace='comments')),

    path('cabinet/', include('cabinetapp.urls', namespace='cabinet')),

    path('likes/', include('likeapp.urls', namespace='likes')),

    path('notification/', include('notificationapp.urls',
                                  namespace='notification')),

    path('captcha/', include('captcha.urls')),
    url(r'^favicon\.png$', RedirectView.as_view(
        url='/static/image/favicon.png',
        permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """Пользователь (На основании стандартного пользователя)"""
    MALE = 'Мужской'
    FEMALE = 'Женский'

    GENDER_CHOICES = (
        (MALE, 'Мужской'),
        (FEMALE, 'Женский'),
    )

    banned = models.DateTimeField(
        verbose_name='забанен до',
        null=True,
        blank=True)
    """забанен до"""

    avatar = models.ImageField(upload_to='users_avatars', blank=True,
                               verbose_name='аватар')
    """аватар"""

    about_me = models.TextField(blank=True, verbose_name='о себе')
    """о себе"""

    gender = models.CharField(max_length=7, blank=True, choices=GENDER_CHOICES,
                              verbose_name='пол')
    """пол"""

    birth_date = models.DateField(blank=True, null=True,
                                  verbose_name='дата рождения')
    """дата рождения"""

    email = models.EmailField(blank=False, null=False, unique=True)
    """электронная почта"""

authapp/forms.py
from datetime import datetime

from captcha.fields import CaptchaField
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, \
    UserChangeForm
from django.core.exceptions import ValidationError
from django.forms import FileInput, DateInput

from authapp.models import User


class UserLoginForm(AuthenticationForm):
    """Форма для аутентификации"""

    class Meta:
        model = User
        fields = ('username', 'password',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class UserRegisterForm(UserCreationForm):
    """Форма для регистрации"""
    Captcha = CaptchaField(label='Подтвердите что вы не робот!')

    class Meta:
        model = User
        fields = ('username', 'email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_email(self):
        email_user = self.cleaned_data['email']
        email_data = User.objects.filter(email=email_user)
        if email_data:
            raise ValidationError(
                'Пользователь с таким email уже зарегистрирован'
            )
        return email_user


class UserEditForm(UserChangeForm):
    """Форма для редактирования юзера"""

    class Meta:
        now = int(datetime.now().year)
        model = User
        fields = (
            'avatar', 'first_name', 'last_name',
            'email', 'gender', 'birth_date', 'about_me',
        )

        widgets = {
            'birth_date': DateInput(attrs={'type': 'date'}),
            'avatar': FileInput(
                attrs={'type': 'button', 'value': 'Редактировать'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['class'] = 'form-group'
            self.fields['about_me'].widget.attrs['rows'] = 4
            field.help_text = ''

            if field_name == 'birth_date' and self.instance.birth_date:
                field.widget = DateInput()

    def clean_birth_date(self):
        now = datetime.now().year
        date_data = self.cleaned_data['birth_date']
        if date_data:
            if 1920 < date_data.year < now:
                return date_data
            raise ValidationError(
                'Неверная дата'
            )


class UserEditAvatarForm(UserChangeForm):
    """Форма для редактирования аватарки"""

    class Meta:
        model = User
        fields = ('avatar',)

        widgets = {
            'avatar': FileInput(
                attrs={'type': 'file'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['class'] = 'form-group'
            field.help_text = ''

authapp/views.py
from datetime import datetime, timedelta

from django.contrib import auth
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import PasswordChangeView
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy

from authapp.forms import UserLoginForm, UserRegisterForm, UserEditForm, \
    UserEditAvatarForm
from authapp.models import User
from knackbook.settings import EMAIL_HOST_USER
from mainapp.models import Section, Article
from notificationapp.models import Notification
from tags.models import Tag


class PasswordEditView(PasswordChangeView):
    """Редактирование пароля"""
    template_name = 'authapp/edit_password.html'
    success_url = reverse_lazy('auth:login')

    def get_context_data(self, **kwargs):
        content = super().get_context_data(**kwargs)
        content['links_section_menu'] = Section.get_links_section_menu()
        content['tags_menu'] = Tag.get_tags_menu()
        content['tags_for_article'] = Tag.get_tags_menu()
        content['notification'] = Notification.notification(self.request)
        return content


def login_user(request):
    """Вход пользователя на сайт"""
    if not request.user.is_authenticated:
        login_form = UserLoginForm(data=request.POST)
        if request.method == 'POST' and login_form.is_valid():
            username = request.POST.get('username')
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
            return HttpResponseRedirect(request.session['next_url'])

        content = {
            'title': 'вход',
            'login_form': login_form,
            'links_section_menu': Section.get_links_section_menu(),
            'tags_menu': Tag.get_tags_menu(),
            'articles': Article.get_articles_five(),
        }

        next_url = request.META.get('HTTP_REFERER')
        request.session['next_url'] = next_url

        return render(request, 'authapp/login.html', content)
    return HttpResponseRedirect(reverse('main:index'))


def logout(request):
    """Разлогирование пользователя"""
    auth.logout(request)
    return HttpResponseRedirect(reverse('auth:login'))


def register(request):
    """Регистрация пользователя"""
    if request.method == 'POST':
        register_form = UserRegisterForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data.get('username')
            password = register_form.cleaned_data.get('password2')
            register_form.save()
            login_user = authenticate(username=username, password=password)
            login(request, login_user)
            send_mail('Регистрация на KnackBook',
                      f'Вы успешно зарегистрированы на KnackBook!\n',
                      EMAIL_HOST_USER,
                      [request.POST.get('email'), ]
                      )
            return HttpResponseRedirect(request.session['next_url'])
    elif not request.user.is_authenticated:
        register_form = UserRegisterForm()
    else:
        return HttpResponseRedirect(reverse('main:index'))

    next_url = request.META.get('HTTP_REFERER')
    request.session['next_url'] = next_url

    content = {
        'title': 'регистрация',
        'register_form': register_form,
        'links_section_menu': Section.get_links_section_menu(),
        'tags_menu': Tag.get_tags_menu(),
        'articles': Article.get_articles_five(),
    }

    return render(request, 'authapp/register.html', content)


def edit_user(request):
    """Редактирование пользователя"""
    if request.user.is_authenticated:
        notification = Notification.objects.filter(
            is_active=True,
            user_to=request.user,
            closed=None,
        )
        user = User.objects.filter(id=request.user.id).first()

        score_article = Article.objects
        score_article_draft = Article.objects.filter(is_active=True,
                                                     is_published=False,
                                                     is_rejected=False,
                                                     is_reviewing=False,
                                                     user=request.user.id)
        if request.user.is_staff:
            score_article = score_article.filter(is_reviewing=True,
                                                 is_active=True)
        elif not request.user.is_staff and not request.user.is_superuser:
            score_article = score_article.filter(is_reviewing=True,
                                                 is_active=True,
                                                 user=request.user.id)

        if request.method == 'POST':
            edit_form = UserEditForm(request.POST, request.FILES,
                                     instance=request.user)
            if edit_form.is_valid():
                edit_form.save()
                return HttpResponseRedirect(reverse('cabinet:cabinet'))

        edit_form = UserEditForm(instance=request.user)

        content = {
            'title': 'редактирование профиля',
            'edit_form': edit_form,
            'links_section_menu': Section.get_links_section_menu(),
            'tags_menu': Tag.get_tags_menu(),
            'articles': Article.get_articles_five(),
            'avatar': user.avatar,
            'score_article': len(score_article),
            'score_article_draft': len(score_article_draft),
            'notification': len(notification)
        }

        return render(request, 'authapp/edit_user.html', content)

    return HttpResponseRedirect(reverse('auth:login'))


def delete_user(request, pk):
    """Удаление учентой записи"""
    if request.user.is_authenticated:
        user = get_object_or_404(User, id=pk)
        if request.method == 'POST':
            if user.is_active:
                user.is_active = False
                user.save()
            return HttpResponseRedirect(reverse('main:index'))

        content = {
            'title': 'удаление профиля',
            'links_section_menu': Section.get_links_section_menu(),
            'tags_menu': Tag.get_tags_menu(),
            'notification': Notification.notification(request)
        }
        return render(request, 'authapp/delete_user.html', content)
    return HttpResponseRedirect(reverse('auth:login'))


def edit_avatar(request):
    """Редактирование аватарки"""
    if request.user.is_authenticated:
        user = User.objects.filter(id=request.user.id).first()

        if request.method == 'POST':
            edit_form = UserEditAvatarForm(request.POST, request.FILES,
                                           instance=request.user)
            if edit_form.is_valid():
                edit_form.save()
                return HttpResponseRedirect(reverse('auth:edit'))

        edit_form = UserEditAvatarForm(instance=request.user)

        content = {
            'title': 'удаление профиля',
            'links_section_menu': Section.get_links_section_menu(),
            'tags_menu': Tag.get_tags_menu(),
            'articles': Article.get_articles_five(),
            'edit_form': edit_form,
            'avatar': user.avatar,
            'notification': Notification.notification(request)
        }
        return render(request, 'authapp/edit_avatar.html', content)

    return HttpResponseRedirect(reverse('auth:login'))


def banned_user(request, pk, article=None):
    """Бан пользователя"""
    if request.user.is_staff:
        user_ban = User.objects.filter(id=pk)
        content = {
            'title': 'блокировка пользователя',
            'links_section_menu': Section.get_links_section_menu(),
            'tags_menu': Tag.get_tags_menu(),
            'notification': Notification.notification(request),
            'user_ban': user_ban.first()
        }
        if not user_ban.first().is_staff:
            if request.method == 'POST':
                now = datetime.now()
                if request.POST.get('day'):
                    user_ban.update(banned=now + timedelta(days=1))
                    Notification.add_notification(
                        content='day',
                        user_to=user_ban.first(),
                        user_from=request.user,
                        article=Article.objects.filter(id=article).first(),
                        comment=None
                    )
                elif request.POST.get('week'):
                    user_ban.update(banned=now + timedelta(weeks=2))
                    Notification.add_notification(
                        content='week',
                        user_to=user_ban.first(),
                        user_from=request.user,
                        article=Article.objects.filter(id=article).first(),
                        comment=None
                    )
                return HttpResponseRedirect(request.session['next_url'])

            return render(request, 'authapp/ban_user.html', content)

        content['not_ban'] = True
        next_url = request.META.get('HTTP_REFERER')
        request.session['next_url'] = next_url
        return render(request, 'authapp/ban_user.html', content)
    return HttpResponseRedirect(reverse('main:index'))

authapp/templates/authapp/ban_user.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        <div class="row">

            <div class="col-2"></div>

            <div class="col-8 g-bold">
                {% if not_ban %}
                    Вы не можете блокировать пользователя
                    "{{ user_ban.username }}" !!!
                    <br><br>
                    <div class="row">
                        <div class="col-8">

                        </div>
                        <div class="col-4">
                            <button class="btn btn-inverse">
                                <a class="" href="#" onclick="history.back();">
                                    Назад
                                </a>
                            </button>
                        </div>
                    </div>
                {% else %}
                    Вы уверены что хотите заблокировать пользователя
                    "{{ user_ban.username }}"?
                    <br><br>

                    <div class="row">
                        <div class="col-5">
                            <button class="btn btn-warning" type="submit"
                                    value="day" name="day">1 День
                            </button>
                        </div>
                        <div class="col-5 align-right">
                            <button class="btn btn-danger" type="submit"
                                    value="week" name="week">2 Недели
                            </button>
                        </div>

                    </div>

                    <br>
                    <hr>
                    <div class="col-12">
                        <button class="btn btn-inverse float-right">
                            <a class="" href="#" onclick="history.back();">
                                Отмена
                            </a>
                        </button>
                    </div>


                    </div>
                {% endif %}
        </div>
    </form>


{% endblock %}

{% block menu %}
    {% include 'mainapp/inc_main_menu.html' %}
{% endblock %}

authapp/templates/authapp/delete_user.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
    <div class="row">

        <div class="col-2">

        </div>

        <div class="col-8 g-bold">
            {% if user.first_name %}
                {{ user.first_name }},
            {% else %}
                {{ user|title }},
            {% endif %} вы уверены что хотите удалить учетную запись?
            <br><br>
            <form action="{% url 'auth:delete_user' user.id %}" method="post">
                {% csrf_token %}

                <div class="row">
                    <div class="col-8">
                        <input class="btn btn-danger" type="submit"
                               value="Удалить">
                    </div>
                    <div class="col-4">
                        <button class="btn btn-inverse">
                            <a class="" href="#" onclick="history.back();">
                                Отмена
                            </a>
                        </button>
                    </div>
                </div>

            </form>
        </div>
    </div>


{% endblock %}

{% block menu %}
    {% include 'mainapp/inc_main_menu.html' %}
{% endblock %}

authapp/templates/authapp/edit_avatar.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
    <div class="row">

        <div class="col-4">
            <img src="/media/{{ avatar }}"
                 class="img-fluid img-circle" alt=" "
                 style="height: 150px; width: 150px">
        </div>

        <div class="col-6 g-bold ">
            {% if user.first_name %}
                {{ user.first_name }},
            {% else %}
                {{ user|title }},
            {% endif %} здесь вы можете изменить аватарку
            <br><br>
            <form action="{% url 'auth:edit_avatar' %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ edit_form.avatar }}
                <br><br>
                <div class="row">
                    <div class="col-8">
                        <input class="btn btn-success" type="submit"
                               value="Сохранить">
                    </div>
                    <div class="col-4">
                        <button class="btn btn-inverse">
                            <a class="" href="{% url 'cabinet:cabinet' %}">
                                Отмена
                            </a>
                        </button>
                    </div>
                </div>

            </form>
        </div>
    </div>


{% endblock %}

{% block menu %}
    {% include 'mainapp/inc_main_menu.html' %}
{% endblock %}

authapp/templates/authapp/edit_password.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
    <div class="row">

        <div class="col-2">
        </div>

        <div class="col-8 g-bold ">
            {% if user.first_name %}
                {{ user.first_name }},
            {% else %}
                {{ user|title }},
            {% endif %} здесь вы можете изменить пароль
            <br><br>
            <form action="{% url 'auth:edit_password' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <br><br>
                <div class="row">
                    <div class="col-8">
                        <input class="btn btn-success" type="submit"
                               value="Сохранить">
                    </div>
                    <div class="col-4">
                        <button class="btn btn-inverse">
                            <a class="" href="{% url 'auth:edit' %}">
                                Отмена
                            </a>
                        </button>
                    </div>
                </div>

            </form>
        </div>
    </div>


{% endblock %}

{% block menu %}
    {% include 'mainapp/inc_main_menu.html' %}
{% endblock %}

authapp/templates/authapp/edit_user.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:edit' %}"
          method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <section>

            <div class="itemListCategory">

                <div>
                    <h1>личный кабинет</h1>
                </div>

                <div class="container">
                    <div class="row size-100">
                        <div class="col-md-3">
                            <img src="/media/{{ avatar }}"
                                 class="img-fluid img-circle" alt=" "
                                 style="height: 150px; width: 150px">


                            <div class="input-group input-group-text ">
                                <a href="{% url 'auth:edit_avatar' %}">{{ edit_form.avatar }}</a>
                            </div>

                        </div>

                        <div class="col-md-9">

                            <div>
                                <h5>
                                    {% if user.is_superuser %}
                                        <p>{{ user }} (администратор)</p>
                                    {% elif user.is_staff %}
                                        <p>{{ user }} (модератор)</p>
                                    {% else %}
                                        <p>{{ user }}</p>
                                    {% endif %}
                                </h5>
                            </div>

                            <div class="align-left small g-notexttransform">
                                О себе:
                            </div>

                            <div class="">
                                <p class="small text-left g-notexttransform">{{ edit_form.about_me }}</p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <br><br>
            <div class="row">
                {% include 'cabinetapp/inc_menu.html' %}
                <div class="col-6">
                    <div class="small">Имя: <span
                            class="g-bold">{{ edit_form.first_name }}</span>
                    </div>
                    <br>

                    <div class="small">Фамилия: <span
                            class="g-bold">{{ edit_form.last_name }}</span>
                    </div>

                    <br>
                    <div class="small">E-mail: <span
                            class="g-bold">{{ edit_form.email }}</span>
                    </div>

                    <br>

                    <div class="small">Пол: <span
                            class="g-bold">{{ edit_form.gender }}</span>
                    </div>

                    <br>
                    <div class="small">Дата рождения: <span
                            class="g-bold">{{ edit_form.birth_date }}</span>
                        <br><br>
                    <div class="">Пароль: <span
                            class="g-bold"></span>
                    </div>
                        <a class="btn btn-success"
                           href="{% url 'auth:edit_password' %}">Изменить
                            пароль</a>
                    </div>
                    <br>


                    <input class="btn-inverse form-control float-left"
                           type="submit"
                           value="Сохранить">

                </div>

            </div>
            <a class="float-right text-error" type="submit"
               href="{% url 'auth:delete_user' pk=user.id %}">Удалить учетную
                запись?</a>
        </section>
    </form>
{% endblock %}

{% block menu %}
    {% include 'mainapp/inc_main_menu.html' %}
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    {% include 'mainapp/inc_main_menu.html' %}

    <form class="form-horizontal size-90" action="{% url 'auth:login' %}"
          method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="btn-inverse form-control" type="submit" value="Войти">
        <a class="float-right" type="submit"
           href="{% url 'auth:register' %}">Нет учетной записи?</a>
    </form>

{% endblock %}

authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    {% include 'mainapp/inc_main_menu.html' %}

    <form class="form-horizontal size-90" action="{% url 'auth:register' %}"
          method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="btn-inverse form-control" type="submit"
               value="Зарегистрироваться">
        <a class="float-right" type="submit"
           href="{% url 'auth:login' %}">Уже есть учетная запись?</a>
    </form>

{% endblock %}