authapp/urls.py
"""
urls for authapp
"""

from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [

    path('login/', authapp.login_user, name='login'),

    path('logout/', authapp.logout, name='logout'),

    path('register/', authapp.register, name='register'),

    path('edit/', authapp.edit_user, name='edit'),

    path('delete-user/<int:pk>/', authapp.delete_user, name='delete_user'),

    path('ban-user/<int:pk>/<int:article>/', authapp.banned_user,
         name='ban_user'),

    path('edit-avatar/', authapp.edit_avatar, name='edit_avatar'),

    path('edit-password/', authapp.PasswordEditView.as_view(),
         name='edit_password'),
]

cabinetapp/urls.py
"""
urls for cabinetapp
"""

from django.urls import path

from .views import main, new_article, my_articles, delete_article, my_drafts, \
    edit_draft, moderation, moderation_check

app_name = "cabinetapp"

urlpatterns = [

    path('', main, name='cabinet'),

    path('new-article/', new_article, name='new_article'),

    path('my-articles/', my_articles, name='my_articles'),

    path('my-drafts/', my_drafts, name='my_drafts'),

    path('delete-article/<int:pk>/', delete_article, name='delete_article'),

    path('edit-draft/<int:pk>', edit_draft, name='edit_draft'),

    path('moderation/', moderation, name='moderation'),

    path('moderation_check/<int:pk>/<int:result>', moderation_check,
         name='moderation_check'),
]

commentapp/urls.py
"""
urls for commentapp
"""

from django.urls import path
from .views import CommentUpdateView, CommentDeleteView, \
    comment_create_for_comment

app_name = "commentapp"

urlpatterns = [
    path('new/<int:pk>/', comment_create_for_comment, name='comment_new'),

    path('edit/<int:pk>/', CommentUpdateView.as_view(), name='comment_edit'),

    path('delete/<int:pk>/', CommentDeleteView.as_view(),
         name='comment_delete'),
]

knackbook/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [

    path('admin/', admin.site.urls, name='admin'),

    path('', include('mainapp.urls', namespace='main')),

    path('auth/', include('authapp.urls', namespace='auth')),

    path('comments/', include('commentapp.urls', namespace='comments')),

    path('cabinet/', include('cabinetapp.urls', namespace='cabinet')),

    path('likes/', include('likeapp.urls', namespace='likes')),

    path('notification/', include('notificationapp.urls',
                                  namespace='notification')),

    path('captcha/', include('captcha.urls')),
    url(r'^favicon\.png$', RedirectView.as_view(
        url='/static/image/favicon.png',
        permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/urls.py
"""
urls for mainapp
"""

from django.urls import path
from .views import main, article_detail_view, ArticlesForTagList,\
    ArticlesForSectionList, ArticlesForSearch, page_help, feedback

app_name = "mainapp"

urlpatterns = [
    path('', main, name='index'),

    path('articles_for_section_list/<int:pk>/',
         ArticlesForSectionList.as_view(),
         name='articles_for_section_list'),

    path('articles_for_tag_list/<int:pk>/', ArticlesForTagList.as_view(),
         name='articles_for_tag_list'),

    path('articles/<int:pk>/', article_detail_view,
         name='article_detail'),

    path('articles/<int:pk>/<int:comment_to>/', article_detail_view,
         name='article_detail_comment_answers'),

    path('articles/search', ArticlesForSearch.as_view(),
         name='articles_search'),

    path('help/', page_help, name='page_help'),

    path('feedback/', feedback, name='feedback'),
]

mainapp/views.py
"""
Контроллеры (Views)
"""

import re
from datetime import datetime

from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils.timezone import utc
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from authapp.models import User
from knackbook.settings import EMAIL_HOST_USER
from likeapp.models import LikeArticle, LikeUser
from notificationapp.models import Notification
from tags.models import Tag
from commentapp.models import Comment
from commentapp.forms import CommentForm
from .models import Section, Article


def main(request):
    """Главная страница"""
    context = {
        'title': 'Knack Book',  # Название закладки в браузере
        'list_name': 'Свежие статьи',  # Наименование списка статей
        'links_section_menu': Section.get_links_section_menu(),
        'tags_menu': Tag.get_tags_menu(),
        'articles': Article.get_articles_five(),
    }
    if request.user.is_authenticated:
        user = User.objects.filter(id=request.user.id)
        if user.first().banned:
            now = datetime.utcnow().replace(tzinfo=utc)
            if now > user.first().banned:
                user.update(banned=None)
        context['notification'] = Notification.notification(request)
    return render(request, 'mainapp/article_list.html', context)


def article_detail_view(request, pk, comment_to=None):
    """Просмотр выбранной статьи и работа с комментариями"""

    # Получаем статью
    # одновременно проверяем на пометку удаления и на признак публикации.
    # Такая дополнительная проверка нужна чтобы нельзя было просмотреть
    # удаленную или неопубликованную статью,
    # вручную указав в адресной строке её url
    if request.user.is_staff or request.user == Article.objects.filter(
            id=pk).first().user:
        article = get_object_or_404(Article, pk=pk, is_active=True)
    else:
        article = get_object_or_404(Article, pk=pk, is_active=True,
                                    is_published=True)
    likes = LikeArticle.objects.filter(is_active=True, article=pk)
    likes_user = LikeUser.objects.filter(is_active=True)
    context = {
        'object': article,  # сама статья

        # общее меню разделов
        'links_section_menu': Section.get_links_section_menu(),

        # общее меню тегов
        'tags_menu': Tag.get_tags_menu(),

        # теги статьи
        'tags_for_article': Tag.objects.filter(article=pk, is_active=True),

        # комментарии для статьи - только первый уровень
        'comments': Comment.get_for_article_level_1(article=pk),

        # комментарий для которого развернут ответ
        'comment_for_answers': comment_to,

        'new_comment': False,

        # количество лайков для статьи
        'likes': len(likes),

        'like_active': len(likes.filter(user=request.user.id)),

        'likes_user': len(
            likes_user.filter(is_active=True, user_to=article.user_id)),

        'like_active_user': len(
            likes_user.filter(is_active=True, user_to=article.user_id,
                              user_from=request.user.id)),
    }

    # Ответы на комментарий
    if comment_to is not None:
        context['answers_for_comment'] = Comment.get_for_comment(
            comment_to=comment_to)

    if request.user.is_authenticated:
        context['notification'] = Notification.notification(request)

    if request.method == 'POST':
        # Комментарий добавлен
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article  # Ссылка на текущую статью
            new_comment.user = request.user  # Ссылка на текущего пользователя
            new_comment.save()
            context['new_comment'] = new_comment
            if article.user != request.user:
                Notification.add_notification(content='комментарий',
                                              user_from=request.user,
                                              user_to=article.user,
                                              article=article,
                                              comment=new_comment
                                              )
            for_moderator = re.search(r'@moderator', new_comment.content)
            if for_moderator:
                moderators = User.objects.filter(is_staff=True)
                for moderator in moderators:
                    Notification.add_notification(content='@moderator',
                                                  user_from=request.user,
                                                  user_to=moderator,
                                                  article=article,
                                                  comment=new_comment
                                                  )

        # context['comment_form'] = comment_form
        context['comment_form'] = CommentForm()
    else:
        context['comment_form'] = CommentForm()

    # Количество комментариев к статье
    context['total_comments'] = Comment.objects.filter(
        article=pk, is_active=True).count()

    return render(request, 'mainapp/article_detail.html', context)


class ArticlesForSectionList(DetailView):
    """Просмотр списка статей для выбранного раздела"""
    model = Section
    template_name = 'mainapp/article_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles'] = Article.get_articles_for_section(self.object)
        context['title'] = 'Статьи в разделе'  # Название закладки в браузере
        context['list_name'] = f'Статьи в разделе: {self.object.name} '
        context['links_section_menu'] = Section.get_links_section_menu()
        context['tags_menu'] = Tag.get_tags_menu()
        if self.request.user.is_authenticated:
            context['notification'] = Notification.notification(self.request)
        return context


class ArticlesForTagList(DetailView):
    """Просмотр списка статей для выбранного тега"""
    model = Tag
    template_name = 'mainapp/article_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles'] = Article.get_articles_for_tag(self.object)
        context['title'] = 'Статьи по тегу'  # Название закладки в браузере
        context['list_name'] = f'Статьи по тегу: {self.object.name} '
        context['links_section_menu'] = Section.get_links_section_menu()
        context['tags_menu'] = Tag.get_tags_menu()
        if self.request.user.is_authenticated:
            context['notification'] = Notification.notification(self.request)
        return context


class ArticlesForSearch(ListView):
    """
    Просмотр списка статей для введенного в строку поиска текста,
    с учетом расширенного поиска, при котором добавляются отборы
    по дате изменения статьи и рейтингу статьи (при его активации)
    """
    model = Article
    template_name = 'mainapp/article_search.html'
    paginate_by = 10

    def get_queryset(self):
        if self.request.GET.get('q') == '':
            queryset = []
        else:
            queryset = Article.get_articles_for_search(self.request)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['queryset'] = self.get_queryset()
        context['links_section_menu'] = Section.get_links_section_menu()
        context['tags_menu'] = Tag.get_tags_menu()
        context['text_search'] = self.request.GET.get('q')
        context['flag_search'] = self.request.GET.get('flag_search')
        context['search_date'] = self.request.GET.get('search_date')
        context['search_rating'] = self.request.GET.get('search_rating')
        context['value'] = self.request.GET.get('q')
        if self.request.user.is_authenticated:
            context['notification'] = Notification.notification(self.request)
        return context


def page_help(request):
    """Страница помощь"""
    context = {
        'title': 'Помощь',
        'links_section_menu': Section.get_links_section_menu(),
        'tags_menu': Tag.get_tags_menu(),
        'articles': Article.get_articles_five(),
    }
    if request.user.is_authenticated:
        context['notification'] = Notification.notification(request)
    return render(request, 'mainapp/page_help.html', context)


@csrf_exempt
def feedback(request):
    """Форма обратной связи"""
    if request.method == 'POST':
        send_mail(request.POST.get('header'),
                  f'{request.POST.get("message")}\n\nСообщение от пользователя'
                  f' - {request.POST.get("name")} - ({request.user},'
                  f' id - {request.user.id}).'
                  f'\nE-mail - {request.POST.get("email")}',
                  EMAIL_HOST_USER,
                  [EMAIL_HOST_USER, ]
                  )
        send_mail(request.POST.get('header'),
                  f'Спасибо за обращение!\nМы получили ваше сообщение'
                  f'\n"{request.POST.get("message")}"\n\n'
                  f'В ближайшее время обязательно вам ответим!',
                  EMAIL_HOST_USER,
                  [request.POST.get('email'), ]
                  )
        return HttpResponseRedirect(request.session['next_url'])

    next_url = request.META.get('HTTP_REFERER')
    request.session['next_url'] = next_url

    context = {
        'title': 'Обратная связь',
        'links_section_menu': Section.get_links_section_menu(),
        'tags_menu': Tag.get_tags_menu(),
    }

    if request.user.is_authenticated:
        context['notification'] = Notification.notification(request)
    return render(request, 'mainapp/feedback.html', context)

mainapp/templates/mainapp/article_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/like_scripts.js' %}"></script>
{% endblock %}

{% block title %}
    Статья
{% endblock %}

{% block menu %}
    {% include 'mainapp/inc_main_menu.html' %}
{% endblock %}

{% block content %}

    <hr>
    <h1>{{ object.title }}</h1>
    <hr>

    <p>{{ object.content|linebreaks }}</p>

    <br>
    {% if user.is_authenticated %}
        {% if like_active == 0 %}

            <div class="col-3 float-right like-article">
                <button class="like-articles" type="submit"
                        data-pk="{{ object.pk }}"
                        value="{{ likes }}">
                    {% include 'likeapp/like_article.html' %}
                </button>
            </div>

        {% else %}

            <div class="col-3 float-right like-article text-danger">
                <button class="like-articles" type="submit"
                        data-pk="{{ object.pk }}"
                        value="{{ likes }}">
                    {% include 'likeapp/like_article.html' %}
                </button>
            </div>

        {% endif %}
    {% else %}

        {% comment %}
        <div class="col-3 float-right">
            <a href="{% url 'auth:login' %}">
                {% include 'likeapp/like_article.html' %}
            </a>
        </div>
        {% endcomment %}
        <div class="col-3 float-right">
            <a href="#zatemnenie">
                {% include 'likeapp/like_article.html' %}
            </a>
        </div>
        <div id="zatemnenie">
            <window>
                <a href="#close_window" class="close_window_right" style="text-align: right;
                    display: block; margin: 0;">&#10008;</a> <br>
                <p style="margin: 0;">Действие доступно только зарегистрированному пользователю </p> <br>
                <a href="{% url 'auth:login' %}" class="">Войти</a>
                <a href="{% url 'auth:register' %}" class="pull-right">Зарегистрироваться</a>
            </window>
        </div>

    {% endif %}

    <div class="row">
        теги:
        <div class="col-6 align-left">
            {% for tag in tags_for_article %}
                <a href="{% url 'mainapp:articles_for_tag_list' pk=tag.pk %}">
                    {{ tag.name }}<br>
                </a>
            {% endfor %}
        </div>
    </div>

    <br>
    <span>Автор:</span>
    {% if like_active_user == 0 %}
        {% if object.user.last_name and object.user.first_name %}
            {{ object.user.first_name }} {{ object.user.last_name }}
            {% if object.user.banned == none %}
                {% if user.is_staff %}<a class="btn-link"
                                         href="{% url 'auth:ban_user' object.user_id object.id %}">BAN</a>
                {% endif %}
            {% else %}
                {% if user.is_staff %}<span class="text-danger">BAN</span>
                {% endif %}
            {% endif %}
            {% if user.is_authenticated %}
                <div class="like-user col-8 float-right">
                    <button class="like-users" type="submit"
                            data-pk="{{ object.user_id }}"
                            value="{{ likes_user }}">
                        {% include 'likeapp/like_user.html' %}
                    </button>
                </div>
            {% else %}
                <div class="like-user col-8 float-right">
                    <a href="#zatemnenie">
                        {% include 'likeapp/like_user.html' %}
                    </a>
                </div>
            {% endif %}
        {% else %}
            {{ object.user.username }}
            {% if object.user.banned == none %}
                {% if user.is_staff %}<a class="btn-link"
                                         href="{% url 'auth:ban_user' object.user_id object.id %}">BAN</a>
                {% endif %}
            {% else %}
                {% if user.is_staff %}<span class="text-danger">BAN</span>
                {% endif %}
            {% endif %}

            {% comment %}
            <div class="like-user col-8 float-right">
                <button class="like-users" type="submit"
                        data-pk="{{ object.user_id }}"
                        value="{{ likes_user }}">
                    {% include 'likeapp/like_user.html' %}
                </button>
            </div>
            {% endcomment %}
            {% if user.is_authenticated %}
                <div class="like-user col-8 float-right">
                    <button class="like-users" type="submit"
                            data-pk="{{ object.user_id }}"
                            value="{{ likes_user }}">
                        {% include 'likeapp/like_user.html' %}
                    </button>
                </div>
            {% else %}
                <div class="like-user col-8 float-right">
                    <a href="#zatemnenie">
                        {% include 'likeapp/like_user.html' %}
                    </a>
                </div>
            {% endif %}

        {% endif %}
    {% else %}
        {% if object.user.last_name and object.user.first_name %}
            {{ object.user.first_name }} {{ object.user.last_name }}
            {% if object.user.banned == none %}
                {% if user.is_staff %}<a class="btn-link"
                                         href="{% url 'auth:ban_user' object.user_id object.id %}">BAN</a>
                {% endif %}
            {% else %}
                {% if user.is_staff %}<span class="text-danger">BAN</span>
                {% endif %}
            {% endif %}
            <div class="like-user text-danger col-8 float-right">
                <button class="like-users" type="submit"
                        data-pk="{{ object.user_id }}"
                        value="{{ likes_user }}">
                    {% include 'likeapp/like_user.html' %}
                </button>
            </div>
        {% else %}
            {{ object.user.username }}
            {% if object.user.banned == none %}
                {% if user.is_staff %}<a class="btn-link"
                                         href="{% url 'auth:ban_user' object.user_id object.id %}">BAN</a>
                {% endif %}
            {% else %}
                {% if user.is_staff %}<span class="text-danger">BAN</span>
                {% endif %}
            {% endif %}
            {% comment %}
            <div class="like-user text-danger col-8 float-right">
                <button class="like-users text-danger" type="submit"
                        data-pk="{{ object.user_id }}"
                        value="{{ likes_user }}">
                    {% include 'likeapp/like_user.html' %}
                </button>-->
            </div>-->
            {% endcomment %}
            {% if user.is_authenticated %}
                <div class="like-user col-8 float-right">
                    <button class="like-users" type="submit"
                            data-pk="{{ object.user_id }}"
                            value="{{ likes_user }}">
                        {% include 'likeapp/like_user.html' %}
                    </button>
                </div>
            {% else %}
                <div class="like-user col-8 float-right">
                    <a href="#zatemnenie">
                        {% include 'likeapp/like_user.html' %}
                    </a>
                </div>
            {% endif %}
        {% endif %}
    {% endif %}
    <p>Создано: {{ object.created|date:"d-E-Y P" }}</p>
    <p>Изменено: {{ object.edited|date:"d-E-Y P" }}</p>

    {% if object.is_reviewing %}
        <p>Статус: На модерации</p>
    {% elif not object.is_rejected and not object.is_reviewing and not object.is_published %}
        <p>Статус: Черновик</p>
    {% endif %}

    {% if object.reject_comment %}
        <p>Причина отклонения: {{ object.reject_comment }}</p>
        <a class="btn btn-link" href="{% url 'cabinet:my_drafts' %}">В
            черновики</a>
    {% endif %}

    <hr>
    {% if object.is_published %}

        <h4>
            Количество комментариев: {{ total_comments }}
        </h4>

        {# Выведем все комментарии к статье #}
        {% for comment in comments %}

            <hr>

            <div>
                <p>
                    Комментарий от {{ comment.user }}
                    {% if user.is_staff %}
                        {% if comment.user.banned == none %}
                            <a class="btn-link"
                               href="{% url 'auth:ban_user' comment.user_id object.id %}">BAN</a>
                        {% else %}
                            <span class="text-danger">BAN</span>
                        {% endif %}
                    {% endif %}
                    ({{ comment.created }}
                    {% if comment.edited > comment.created %}
                        - изменен {{ comment.edited }}
                    {% endif %}
                    )
                </p>

                {% if comment.comment_to %}
                    <p>
                        в ответ на комментарий от {{ comment.comment_to.user }}
                        ({{ comment.comment_to.created }})
                    </p>
                {% endif %}

                {{ comment.content|linebreaks }}
                <br>

                {% if not comment.comment_level_1 and comment.answers_count > 0 and comment.pk != comment_for_answers %}
                    <a href="{% url 'mainapp:article_detail_comment_answers' pk=object.pk comment_to=comment.pk %}">Развернуть</a>
                    ({{ comment.answers_count }})
                {% endif %}

                {% if user.is_authenticated %}
                    {% if not user.banned %}
                        <a href="{% url 'commentapp:comment_new' pk=comment.pk %}">Ответить</a>
                        {% if user == comment.user %}
                            <a href="{% url 'commentapp:comment_edit' pk=comment.pk %}">Изменить</a>
                        {% endif %}
                        {% if user == comment.user or user.is_staff %}
                            <a href="{% url 'commentapp:comment_delete' pk=comment.pk %}">Удалить</a>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>

            {% if comment.pk == comment_for_answers %}
                {# Если выбран режим просмотра ответов к комментарию то выводим ответы #}
                {# здесь практически продублирован код для вывода обычного комментария #}

                {% for answer in answers_for_comment %}

                    <hr>
                    {# Если комментарий второго уровня (ответ) то у него специальный класс со смещением #}
                    <div class="div_article_comment_2">
                        <p>
                            Комментарий от {{ answer.user }}
                            {% if answer.user.banned == none %}
                                {% if user.is_staff %}<a class="btn-link"
                                                         href="{% url 'auth:ban_user' answer.user_id object.id %}">BAN</a>
                                {% endif %}
                            {% else %}
                                <span class="text-danger">BAN</span>
                            {% endif %}
                            ({{ answer.created }}
                            {% if answer.edited > answer.created %}
                                - изменен {{ answer.edited }}
                            {% endif %}
                            )
                        </p>

                        {% if answer.comment_to %}
                            <p>
                                в ответ на комментарий
                                от {{ answer.comment_to.user }}
                                ({{ answer.comment_to.created }})
                            </p>
                        {% endif %}

                        {{ answer.content|linebreaks }}
                        <br>

                        {% if user.is_authenticated %}
                            {% if not user.banned %}
                                <a href="{% url 'commentapp:comment_new' pk=answer.pk %}">Ответить</a>
                                {% if user == answer.user %}
                                    <a href="{% url 'commentapp:comment_edit' pk=answer.pk %}">Изменить</a>
                                {% endif %}
                                {% if user == comment.user or user.is_staff %}
                                    <a href="{% url 'commentapp:comment_delete' pk=answer.pk %}">Удалить</a>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    </div>

                {% endfor %}

            {% endif %}

        {% empty %}
            <p>Пока комментариев нет</p>
        {% endfor %}

        {% if new_comment %}
            <h4>Ваш комментарий был добавлен</h4>
        {% endif %}

        {% if user.is_authenticated %}
            {% if not user.banned %}
                <h4>Напишите ваш комментарий:</h4>

                <form action="." method="post">
                    {{ comment_form.as_p }}
                    {% csrf_token %}
                    <p><input type="submit" value="Добавить"></p>
                </form>
            {% endif %}
        {% else %}
            <h4>Комментарии могут добавлять только авторизированные
                пользователи </h4>
        {% endif %}
    {% endif %}

    {% if user.is_staff and object.is_reviewing %}
        {% include 'cabinetapp/moderation.html' %}
    {% endif %}

    {% if user.is_staff and object.is_published %}
        {% include 'cabinetapp/moderation.html' %}
    {% endif %}

{% endblock %}

mainapp/templates/mainapp/article_search.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}
    Статьи
{% endblock %}

{% block menu %}
    {% include 'mainapp/inc_main_menu.html' %}
{% endblock %}

{% block content %}
    <hr>
    {% if text_search == "" %}
        <h1>Задан пустой поиск, введите текст для поиска...</h1>
        <hr>
    {% else %}
        <h1>Статьи по запросу: {{ text_search }}</h1>
        <hr>
        {% if object_list %}
            {% for object in object_list %}
                    <div class="col-12 well-small">

                        <div class="catItemView groupLeading">

                            <div class="catItemHeader">
                                <h3 class="catItemTitle">
                                    <a href="{% url 'mainapp:article_detail' pk=object.pk %}">
                                        {{ object.title }}
                                    </a>
                                </h3>
                            </div>
                            <div class="small align-left">
                                Рейтинг: {{ object.likes_count }}
                            </div>
                            <div class="small align-right">
                                {{ object.edited|date:"d-E-Y" }}
                            </div>

                            <div class="catItemReadMore">
                                <a class="k2ReadMore"
                                   href="{% url 'mainapp:article_detail' pk=object.pk %}">
                                    Читать ... </a>
                            </div>

                            <div class="clr"></div>
                            <div class="clr"></div>

                        </div>

                    </div>
<!--                <a href="{% url 'mainapp:article_detail' pk=object.pk %}">{{ object.title }} ({{ object.edited|date:"d-E-Y P" }}) </a>-->
<!--                <br>-->
            {% endfor %}
            <div class="pagination-right">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?q={{ request.GET.q }}&page=1">&laquo; В начало</a>
                    <a href="?q={{ request.GET.q }}&page={{ page_obj.previous_page_number }}">Предыдущая</a>
                {% endif %}
                <span class="current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?q={{ request.GET.q }}&page={{ page_obj.next_page_number }}">Следующая</a>
                    <a href="?q={{ request.GET.q }}&page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
                {% endif %}
            </span>
            </div>
        {% else %}
            <h4>Ничего не найдено</h4>
        {% endif %}
    {% endif %}
{% endblock %}

mainapp/templates/mainapp/section_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}
    Разделы
{% endblock %}

{% block menu %}
    {% include 'mainapp/inc_main_menu.html' %}
{% endblock %}

{% block content %}
    <hr>
    <h1>Разделы</h1>
    <hr>

    {% for object in object_list %}
        <a href="{% url 'mainapp:articles_for_section_list' pk=object.pk %}">{{ object.name }} </a>
        <br>
    {% endfor %}

{% endblock %}