authapp/urls.py
"""
urls for authapp
"""

from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [

    path('login/', authapp.login_user, name='login'),

    path('logout/', authapp.logout, name='logout'),

    path('register/', authapp.register, name='register'),

    path('edit/', authapp.edit_user, name='edit'),

    path('delete-user/<int:pk>/', authapp.delete_user, name='delete_user'),

    path('ban-user/<int:pk>/<int:article>/', authapp.banned_user,
         name='ban_user'),

    path('edit-avatar/', authapp.edit_avatar, name='edit_avatar'),

    path('edit-password/', authapp.PasswordEditView.as_view(),
         name='edit_password'),
]

cabinetapp/urls.py
"""
urls for cabinetapp
"""

from django.urls import path

from .views import main, new_article, my_articles, delete_article, my_drafts, \
    edit_draft, moderation, moderation_check

app_name = "cabinetapp"

urlpatterns = [

    path('', main, name='cabinet'),

    path('new-article/', new_article, name='new_article'),

    path('my-articles/', my_articles, name='my_articles'),

    path('my-drafts/', my_drafts, name='my_drafts'),

    path('delete-article/<int:pk>/', delete_article, name='delete_article'),

    path('edit-draft/<int:pk>', edit_draft, name='edit_draft'),

    path('moderation/', moderation, name='moderation'),

    path('moderation_check/<int:pk>/<int:result>', moderation_check,
         name='moderation_check'),
]

knackbook/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [

    path('admin/', admin.site.urls, name='admin'),

    path('', include('mainapp.urls', namespace='main')),

    path('auth/', include('authapp.urls', namespace='auth')),

    path('comments/', include('commentapp.urls', namespace='comments')),

    path('cabinet/', include('cabinetapp.urls', namespace='cabinet')),

    path('likes/', include('likeapp.urls', namespace='likes')),

    path('notification/', include('notificationapp.urls',
                                  namespace='notification')),

    path('captcha/', include('captcha.urls')),
    url(r'^favicon\.png$', RedirectView.as_view(
        url='/static/image/favicon.png',
        permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/urls.py
"""
urls for mainapp
"""

from django.urls import path
from .views import main, article_detail_view, ArticlesForTagList,\
    ArticlesForSectionList, ArticlesForSearch, page_help, feedback

app_name = "mainapp"

urlpatterns = [
    path('', main, name='index'),

    path('articles_for_section_list/<int:pk>/',
         ArticlesForSectionList.as_view(),
         name='articles_for_section_list'),

    path('articles_for_tag_list/<int:pk>/', ArticlesForTagList.as_view(),
         name='articles_for_tag_list'),

    path('articles/<int:pk>/', article_detail_view,
         name='article_detail'),

    path('articles/<int:pk>/<int:comment_to>/', article_detail_view,
         name='article_detail_comment_answers'),

    path('articles/search', ArticlesForSearch.as_view(),
         name='articles_search'),

    path('help/', page_help, name='page_help'),

    path('feedback/', feedback, name='feedback'),
]

notificationapp/urls.py
"""
urls for notificationapp
"""

from django.urls import path
from notificationapp.views import notifications, notification_edit, \
    notification_delete

app_name = "notificationapp"

urlpatterns = [
    path('', notifications, name='notification'),
    path('notification_edit/<int:pk>/', notification_edit,
         name='notification_edit'),
    path('notification_delete/<int:pk>/', notification_delete,
         name='notification_delete'),
]

notificationapp/models.py
"""Модели данных"""

from django.db import models
from django.conf import settings
from mainapp.models import Article
from commentapp.models import Comment


class Notification(models.Model):
    """Уведомление"""

    content = models.TextField(verbose_name='содержимое уведомления')
    """содержимое уведомления"""

    user_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='note_user_to',
        on_delete=models.CASCADE,
        verbose_name='пользователь-получатель',
        null=False)
    """пользователь для кого уведомление"""

    user_from = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='note_user_from',
        on_delete=models.CASCADE,
        verbose_name='пользователь-создатель',
        null=False)
    """пользователь от кого уведомление"""

    created = models.DateTimeField(verbose_name='создано', auto_now_add=True)
    """дата и время создания уведомления"""

    closed = models.DateTimeField(verbose_name='закрыто', null=True,
                                  blank=True)
    """дата и время закрытия уведомления"""

    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
        verbose_name='статья',
        null=True,
        blank=True)
    """статья"""

    comment = models.ForeignKey(
        Comment,
        on_delete=models.CASCADE,
        verbose_name='комментарий',
        null=True,
        blank=True)
    """комментарий"""

    is_active = models.BooleanField(
        verbose_name='актив',
        default=True,
        db_index=True)
    """
    True - уведомление активно
    False - уведомление удалено
    """

    @staticmethod
    def add_notification(**kwargs):
        if not kwargs['content']:
            kwargs['content'] = 'одобрено'
        Notification.objects.create(
            content=kwargs['content'],
            user_to=kwargs['user_to'],
            user_from=kwargs['user_from'],
            article=kwargs['article'],
            comment=kwargs['comment']
        )

    @staticmethod
    def notification(request):
        notification = Notification.objects.filter(
            is_active=True,
            user_to=request.user,
            closed=None,
        )
        return len(notification)

notificationapp/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse

from mainapp.models import Article, Section
from notificationapp.models import Notification
from tags.models import Tag


def notifications(request):
    """Уведомления"""
    if request.user.is_authenticated:
        notifications = Notification.objects
        score_article_draft = Article.objects.filter(is_active=True,
                                                     is_published=False,
                                                     is_reviewing=False,
                                                     user=request.user.id)
        score_article = Article.objects

        if request.user.is_staff:
            score_article = score_article.filter(is_reviewing=True,
                                                 is_active=True)
        elif not request.user.is_staff and not request.user.is_superuser:
            score_article = score_article.filter(is_reviewing=True,
                                                 is_active=True,
                                                 user=request.user.id)

        content = {
            'title': 'уведомления',
            'links_section_menu': Section.get_links_section_menu(),
            'tags_menu': Tag.get_tags_menu(),
            'score_article': len(score_article),
            'score_article_draft': len(score_article_draft),
            'notifications': notifications.filter(user_to=request.user.id,
                                                  is_active=True).order_by(
                '-created'),
            'notification': len(notifications.filter(
                is_active=True,
                user_to=request.user,
                closed=None,
            ))
        }

        return render(request, 'notificationapp/notification.html', content)

    return HttpResponseRedirect(reverse('auth:login'))


@login_required
def notification_edit(request, pk):
    """Изменение статуса уведомления"""
    if request.is_ajax():
        notification = Notification.objects.filter(id=pk,
                                                   closed=None).first()
        if notification:
            notification.closed = datetime.now()
            notification.save()

        return JsonResponse({'result': ''})


@login_required
def notification_delete(request, pk):
    """Удаление уведомления"""
    notifications = Notification.objects

    notification = notifications.filter(id=pk).first()
    if notification:
        notification.is_active = False
        notification.save()

    return JsonResponse({'result': ''})

notificationapp/templates/notificationapp/notification.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/notification_scripts.js' %}"></script>
{% endblock %}

{% block content %}
    <section>

        <div class="itemListCategory">

            <div>
                <h1>уведомления</h1>
            </div>

            <div class="container">
                <div class="row size-100">

                    <div class="col-9">

                        <div>
                            <h5 class="align-right">
                                {% if user.is_superuser %}
                                    <p>{{ user }} (администратор)</p>
                                {% elif user.is_staff %}
                                    <p>{{ user }} (модератор)</p>
                                {% else %}
                                    <p>{{ user }}</p>
                                {% endif %}
                            </h5>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <br><br>
        <div class="row">
            {% include 'cabinetapp/inc_menu.html' %}
            <div class="col-8">
                {% if notifications %}
                    {% for notification in notifications %}
                        <div class="row pb-3" id="n{{ notification.id }}">
                            <div class="col-12 table-bordered">
                                <p class="">

                                    {% if notification.content == 'лайк юзер' %}
                                        <p class="center">Вам поставил лайк
                                            <span class="text-danger">❤</span>
                                            - {{ notification.user_from }}</p>

                                    {% elif notification.content == '@moderator' %}
                                        <p>В статье <a
                                                href="{% url 'mainapp:article_detail' notification.article.id %}">"{{ notification.article }}"</a>
                                            - жалоба!</p>
                                        <p>Комментарий
                                            "{{ notification.comment }}"</p>

                                    {% elif notification.content == 'day' %}
                                        <p class="text-danger center">
                                            ❗ {{ user|title }}, ваша учетная
                                            запись заблокирована на 1 день
                                            ❗</p>
                                    {% elif notification.content == 'week' %}
                                        <p class="text-danger center">
                                            ❗ {{ user|title }}, ваша учетная
                                            запись заблокирована на 2 недели
                                            ❗</p>
                                    {% else %}
                                        <span class="g-bold">Ваша статья:</span>

                                        {% if notification.content != 'статья удалена' %}
                                            <span>
                                            <a class="text-success cancel-link"
                                               href="{% url 'mainapp:article_detail' pk=notification.article.id %}">
                                    "{{ notification.article.title }}"</a>
                                        {% else %}
                                            "
                                            <span>{{ notification.article.title }}"</span>
                                        {% endif %}

                                    - </span>
                                        {% if notification.content == 'одобрено' %}
                                            <span class="text-success">опубликована на сайт</span>
                                        {% elif notification.content == 'статья удалена' %}
                                            <span class="text-danger">была
                                    удалена с сайта</span>
                                        {% elif notification.content == 'комментарий' %}
                                            <span>Добавлен комментарий</span>
                                        {% elif notification.content == 'лайк статья' %}
                                            <span class="text-danger">Поставил лайк ❤</span>
                                            <span>- {{ notification.user_from }}</span>
                                        {% else %}
                                            <span class="text-danger">была
                                    отклонена в публикации</span>{% endif %}

                                    {% endif %}
                                <div>
                                    {% if notification.closed %}
                                        <div class="">
                                            <input class="float-left btn-mini btn-success"
                                                   type="reset"
                                                   name="button"
                                                   value="Прочитано">
                                        </div>
                                    {% else %}
                                        <div class="edit-button">
                                            <input class="edit-buttons float-left btn-mini btn-info"
                                                   type="submit"
                                                   name="view"
                                                   id="{{ notification.id }}"
                                                   data-pk="{{ notification.id }}"
                                                   value="Пометить как прочитано">
                                        </div>
                                    {% endif %}
                                    <div class="delete-button">
                                        <input class="delete-buttons float-right btn-mini btn-danger"
                                               type="submit" name="delete"
                                               id="{{ notification.id }}"
                                               data-pk="{{ notification.id }}"
                                               value="Удалить">
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>У вас нет уведомлений</p>
                {% endif %}

            </div>

        </div>

        <div class="row">

            <div class="col-12">
                <a class="btn float-right btn-inverse"
                   href="{% url 'cabinet:cabinet' %}">
                    Личный кабинет
                </a>
            </div>
        </div>


    </section>
{% endblock %}

{% block menu %}
    {% include 'mainapp/inc_main_menu.html' %}
{% endblock %}