authapp/urls.py
"""
urls for authapp
"""

from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [

    path('login/', authapp.login_user, name='login'),

    path('logout/', authapp.logout, name='logout'),

    path('register/', authapp.register, name='register'),

    path('edit/', authapp.edit_user, name='edit'),

    path('delete-user/<int:pk>/', authapp.delete_user, name='delete_user'),

    path('ban-user/<int:pk>/<int:article>/', authapp.banned_user,
         name='ban_user'),

    path('edit-avatar/', authapp.edit_avatar, name='edit_avatar'),

    path('edit-password/', authapp.PasswordEditView.as_view(),
         name='edit_password'),
]

cabinetapp/urls.py
"""
urls for cabinetapp
"""

from django.urls import path

from .views import main, new_article, my_articles, delete_article, my_drafts, \
    edit_draft, moderation, moderation_check

app_name = "cabinetapp"

urlpatterns = [

    path('', main, name='cabinet'),

    path('new-article/', new_article, name='new_article'),

    path('my-articles/', my_articles, name='my_articles'),

    path('my-drafts/', my_drafts, name='my_drafts'),

    path('delete-article/<int:pk>/', delete_article, name='delete_article'),

    path('edit-draft/<int:pk>', edit_draft, name='edit_draft'),

    path('moderation/', moderation, name='moderation'),

    path('moderation_check/<int:pk>/<int:result>', moderation_check,
         name='moderation_check'),
]

knackbook/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [

    path('admin/', admin.site.urls, name='admin'),

    path('', include('mainapp.urls', namespace='main')),

    path('auth/', include('authapp.urls', namespace='auth')),

    path('comments/', include('commentapp.urls', namespace='comments')),

    path('cabinet/', include('cabinetapp.urls', namespace='cabinet')),

    path('likes/', include('likeapp.urls', namespace='likes')),

    path('notification/', include('notificationapp.urls',
                                  namespace='notification')),

    path('captcha/', include('captcha.urls')),
    url(r'^favicon\.png$', RedirectView.as_view(
        url='/static/image/favicon.png',
        permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mainapp/urls.py
"""
urls for mainapp
"""

from django.urls import path
from .views import main, article_detail_view, ArticlesForTagList,\
    ArticlesForSectionList, ArticlesForSearch, page_help, feedback

app_name = "mainapp"

urlpatterns = [
    path('', main, name='index'),

    path('articles_for_section_list/<int:pk>/',
         ArticlesForSectionList.as_view(),
         name='articles_for_section_list'),

    path('articles_for_tag_list/<int:pk>/', ArticlesForTagList.as_view(),
         name='articles_for_tag_list'),

    path('articles/<int:pk>/', article_detail_view,
         name='article_detail'),

    path('articles/<int:pk>/<int:comment_to>/', article_detail_view,
         name='article_detail_comment_answers'),

    path('articles/search', ArticlesForSearch.as_view(),
         name='articles_search'),

    path('help/', page_help, name='page_help'),

    path('feedback/', feedback, name='feedback'),
]

notificationapp/urls.py
"""
urls for notificationapp
"""

from django.urls import path
from notificationapp.views import notifications, notification_edit, \
    notification_delete

app_name = "notificationapp"

urlpatterns = [
    path('', notifications, name='notification'),
    path('notification_edit/<int:pk>/', notification_edit,
         name='notification_edit'),
    path('notification_delete/<int:pk>/', notification_delete,
         name='notification_delete'),
]

cabinetapp/models.py
from django.db import models

# Create your models here.

cabinetapp/forms.py
from django.forms import ModelForm

from mainapp.models import Article


class NewArticleForm(ModelForm):
    """Форма новой статьи"""

    class Meta:
        model = Article
        fields = ('title', 'content', 'sections', 'tags')

    def __init__(self, data=None, *args, **kwargs):
        super().__init__(data=data, *args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['tags'].required = False
        self.fields['content'].required = False
        self.fields['sections'].required = False

cabinetapp/views.py
from datetime import datetime

from django.contrib.auth.decorators import user_passes_test, login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.timezone import utc

from authapp.models import User
from cabinetapp.forms import NewArticleForm
from likeapp.models import LikeUser
from mainapp.models import Section, Article
from notificationapp.models import Notification
from tags.models import Tag


def update_is_reviewing(id_article):
    """Отправление статьи на модерацию"""
    Article.objects.filter(id=id_article).update(is_reviewing=True,
                                                 is_published=False,
                                                 is_rejected=False)


def save_draft(id_article):
    """Сохранения черновика"""
    Article.objects.filter(id=id_article).update(is_reviewing=False,
                                                 is_published=False)


def update_article_data(data, pk):
    """Обновление статьи в базе"""
    Article.objects.filter(id=pk).update(
        title=data.get('title'),
        content=data.get('content'),
    )

    Article.objects.filter(id=pk).first().sections.clear()
    Article.objects.filter(id=pk).first().tags.clear()
    for section in data.getlist('sections'):
        Article.objects.filter(id=pk).first().sections.add(section)
    for tag in data.getlist('tags'):
        Article.objects.filter(id=pk).first().tags.add(tag)


def main(request):
    """Главная страница личного кабинета"""
    if request.user.is_authenticated:
        user = User.objects.filter(id=request.user.id)
        likes = LikeUser.objects.filter(user_to=request.user.id)
        if user.first().banned:
            now = datetime.utcnow().replace(tzinfo=utc)
            if now > user.first().banned:
                user.update(banned=None)
        score_article = Article.objects
        score_article_draft = Article.objects.filter(is_active=True,
                                                     is_published=False,
                                                     is_reviewing=False,
                                                     user=request.user.id)
        notification = Notification.objects.filter(
            is_active=True,
            user_to=request.user,
            closed=None,
        )
        if request.user.is_staff:
            score_article = score_article.filter(is_reviewing=True,
                                                 is_active=True)
        elif not request.user.is_staff and not request.user.is_superuser:
            score_article = score_article.filter(is_reviewing=True,
                                                 is_active=True,
                                                 user=request.user.id)

        content = {
            'title': 'личный кабинет',
            'links_section_menu': Section.get_links_section_menu(),
            'tags_menu': Tag.get_tags_menu(),
            'articles': Article.get_articles_five(),
            'user': request.user,
            'avatar': user.first().avatar,
            'about_me': user.first().about_me,
            'gender': user.first().gender,
            'birth_date': user.first().birth_date,
            'last_name': user.first().last_name,
            'first_name': user.first().first_name,
            'email': user.first().email,
            'score_article': len(score_article),
            'score_article_draft': len(score_article_draft),
            'notification': len(notification),
            'rating': len(likes),
        }

        return render(request, 'cabinetapp/cabinet.html', content)
    return HttpResponseRedirect(reverse('main:index'))


@user_passes_test(lambda u: not u.banned if u.is_authenticated else '')
def new_article(request):
    """Создание новой статьи"""
    if request.user.is_authenticated:
        form = NewArticleForm(request.POST)

        if request.method == 'POST':
            if form.is_valid():
                create_article = form.save(commit=False)
                create_article.user_id = request.user.id
                if form.data.get('save'):
                    create_article.is_reviewing = True
                form.save()

                return HttpResponseRedirect(reverse('cabinet:cabinet'))

        content = {
            'title': 'личный кабинет',
            'links_section_menu': Section.get_links_section_menu(),
            'tags_menu': Tag.get_tags_menu(),
            'form': form,
            'notification': Notification.notification(request)
        }
        return render(request, 'cabinetapp/new_article.html', content)
    return HttpResponseRedirect(reverse('auth:login'))


def my_articles(request):
    """Просмотр моих опубликованных статей"""
    if request.user.is_authenticated:
        user = request.user.id
        articles = Article.objects.filter(
            is_active=True,
            is_published=True,
            user=user
        )

        content = {
            'title': 'мои статьи',
            'links_section_menu': Section.get_links_section_menu(),
            'tags_menu': Tag.get_tags_menu(),
            'articles': articles,
            'notification': Notification.notification(request)
        }

        return render(request, 'cabinetapp/my_article.html', content)

    return HttpResponseRedirect(reverse('auth:login'))


def delete_article(request, pk):
    """Удаление статьи"""
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)

        if request.user.id == article.user_id or request.user.is_staff:

            if request.method == 'POST':
                if article.is_active:
                    article.is_active = False
                    article.is_published = False
                    article.save()
                    if request.user != article.user:
                        Notification.add_notification(
                            content='статья удалена',
                            user_from=request.user,
                            user_to=article.user,
                            article=article,
                            comment=None
                            )
                    return HttpResponseRedirect(request.session['next_url'])

            next_url = request.META.get('HTTP_REFERER')
            request.session['next_url'] = next_url

            content = {
                'title': 'удаление статьи',
                'links_section_menu': Section.get_links_section_menu(),
                'tags_menu': Tag.get_tags_menu(),
                'article': article,
                'notification': Notification.notification(request)
            }
            return render(request, 'cabinetapp/delete_article.html', content)

        return HttpResponseRedirect(reverse('cabinet:my_articles'))

    return HttpResponseRedirect(reverse('auth:login'))


def my_drafts(request):
    """Просмотр черновиков"""
    if request.user.is_authenticated:
        user = request.user.id
        articles = Article.objects.filter(
            is_active=True,
            is_published=False,
            is_reviewing=False,
            user=user
        )

        content = {
            'title': 'черновики',
            'links_section_menu': Section.get_links_section_menu(),
            'tags_menu': Tag.get_tags_menu(),
            'articles': articles,
            'notification': Notification.notification(request)
        }

        return render(request, 'cabinetapp/my_article.html', content)

    return HttpResponseRedirect(reverse('auth:login'))


def edit_draft(request, pk):
    """Редактирование черновика"""
    if request.user.is_authenticated:
        article = Article.objects.filter(id=pk).first()
        article_published = Article.objects.filter(id=pk,
                                                   is_published=True).first()

        if request.user.id == article.user_id:

            if request.method == 'POST':
                form = NewArticleForm(request.POST)

                if form.is_valid():
                    form.save(commit=False)
                    data = form.data
                    if form.data.get('draft'):
                        save_draft(pk)
                    elif form.data.get('save'):
                        update_is_reviewing(pk)
                    update_article_data(data, pk)

                    return HttpResponseRedirect(reverse('cabinet:my_drafts'))

            form = NewArticleForm(instance=article)

            content = {
                'title': 'редактирование',
                'links_section_menu': Section.get_links_section_menu(),
                'tags_menu': Tag.get_tags_menu(),
                'form': form,
                'article': article,
                'article_published': article_published,
                'notification': Notification.notification(request)
            }

            return render(request, 'cabinetapp/new_article.html', content)

        return HttpResponseRedirect(reverse('cabinet:my_drafts'))

    return HttpResponseRedirect(reverse('auth:login'))


def moderation(request):
    """Список статей на модерации"""
    if request.user.is_authenticated:
        if request.user.is_staff:
            articles = Article.objects.filter(is_reviewing=True,
                                              is_active=True)
        else:
            articles = Article.objects.filter(user=request.user.id,
                                              is_reviewing=True,
                                              is_active=True)

        content = {
            'title': 'модерация',
            'links_section_menu': Section.get_links_section_menu(),
            'tags_menu': Tag.get_tags_menu(),
            'articles': articles,
            'notification': Notification.notification(request)
        }

        return render(request, 'cabinetapp/my_article.html', content)

cabinetapp/templates/cabinetapp/cabinet.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <section>

        <div class="itemListCategory">

            <div>
                <h1>личный кабинет</h1>
            </div>

            <div class="container">
                <div class="row size-100">
                    <div class="col-md-3">
                        <img src="/media/{{ avatar }}"
                             class="img-fluid img-circle" alt=" "
                             style="height: 150px; width: 150px">
                    </div>

                    <div class="col-md-9">

                        <div>
                            <h5>
                                {% if user.is_superuser %}
                                    <p>{{ user }} (администратор)</p>
                                {% elif user.is_staff %}
                                    <p>{{ user }} (модератор)</p>
                                {% else %}
                                    {% if user.banned %}
                                        <p class="text-danger">{{ user }}</p>
                                        <small class="text-danger">Заблокирован
                                            до {{ user.banned }}</small>
                                    {% else %}
                                        <p>{{ user }}</p>
                                    {% endif %}
                                {% endif %}

                                <small class="g-notexttransform float-left">Рейтинг: {{ rating }}</small>

                                <br>

                            </h5>
                        </div>

                        <div class="align-left small g-notexttransform">
                            О себе:
                        </div>

                        <div class="table-bordered">
                            {% if about_me %}
                                <p class="small text-left g-notexttransform">{{ about_me }}</p>
                            {% else %}
                                <a class="small float-left text-error g-notexttransform"
                                   href="{% url 'auth:edit' %}">добавить</a>
                            {% endif %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <br><br>
        <div class="row">
            {% include 'cabinetapp/inc_menu.html' %}
            <div class="col-6">

                {% if first_name %}
                    <div>Имя: <span
                            class="g-bold">{{ first_name|title }}</span></div>
                {% else %}
                    <div>Имя: <a class="small text-error g-notexttransform"
                                 href="{% url 'auth:edit' %}">добавить</a>
                {% endif %}

                {% if last_name %}
                    <div>Фамилия: <span
                            class="g-bold">{{ last_name|title }}</span></div>
                {% else %}
                    <div>Фамилия: <a class="small text-error g-notexttransform"
                                     href="{% url 'auth:edit' %}">добавить</a>
                {% endif %}

                {% if email %}
                    <div>E-mail: <span class="g-bold">{{ email }}</span></div>
                {% else %}
                    <div>E-mail: <a class="small text-error g-notexttransform"
                                    href="{% url 'auth:edit' %}">добавить</a>
                {% endif %}

                <br><br>

                {% if gender %}
                    <div>Пол: <span class="g-bold">{{ gender }}</span></div>
                {% else %}
                    <div>Пол: <a class="small text-error g-notexttransform"
                                 href="{% url 'auth:edit' %}">добавить</a>
                    </div>
                {% endif %}


                {% if birth_date %}
                    <div>Дата рождения: <span
                            class="g-bold">{{ birth_date }}</span></div>
                {% else %}
                    <div>Дата рождения: <a
                            class="small text-error g-notexttransform"
                            href="{% url 'auth:edit' %}">добавить</a>
                    </div>
                {% endif %}

                </div>
                </div>

    </section>
{% endblock %}

{% block menu %}
    {% include 'mainapp/inc_main_menu.html' %}
{% endblock %}

cabinetapp/templates/cabinetapp/delete_article.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
    <div class="row">

        <div class="col-2">

        </div>

        <div class="col-8 g-bold">
            {% if user.first_name %}
                {{ user.first_name }},
            {% else %}
                {{ user|title }},
            {% endif %} вы уверены что хотите удалить статью?
            <br><br>
            <form action="{% url 'cabinet:delete_article' article.id %}"
                  method="post">
                {% csrf_token %}

                <div class="row">
                    <div class="col-6">
                        <input class="btn btn-danger" type="submit"
                               value="Удалить">
                    </div>
                    {% if user.is_staff %}

                        <div class="col-4">
                            <button class="btn btn-inverse">
                                <a class=""
                                   href="#" onclick="history.back();">
                                    Отмена
                                </a>
                            </button>
                        </div>

                    {% elif user.is_authenticated %}

                        <div class="col-4">
                            <button class="btn btn-inverse">
                                <a class=""
                                   href="#" onclick="history.back();">
                                    Отмена
                                </a>
                            </button>
                        </div>

                    {% endif %}
                </div>

            </form>
        </div>
    </div>


{% endblock %}

{% block menu %}
    {% include 'mainapp/inc_main_menu.html' %}
{% endblock %}

cabinetapp/templates/cabinetapp/inc_menu.html
{% load static %}

<div class="g-grid col-3">

    <div class="g-block size-100 align-left">
        <nav class="g-main-nav">
            <ul>
                {% if user.banned %}
                    <li>
                        <span class="">
                            <span class="g-menu-item-title g-bold text-danger">Новая статья</span>
                        </span>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'cabinet:new_article' %}">
                            <span class="">
                                <span class="g-menu-item-title g-bold">Новая статья</span>
                            </span>
                        </a>
                    </li>
                {% endif %}

                <li>
                    <a href="{% url 'cabinet:my_articles' %}">
                            <span class="g-menu-item-content">
                                <span class="g-menu-item-title g-bold">Мои статьи</span>
                            </span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'cabinet:my_drafts' %}">
                        <span class="g-menu-item-content">
                            <span class="g-menu-item-title g-bold">Черновики
                                {% if score_article_draft != 0 %}
                                    ({{ score_article_draft }})
                                {% endif %}
                            </span>
                        </span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'auth:edit' %}">
                        <span class="g-menu-item-content">
                            <span class="g-menu-item-title g-bold {% if request.resolver_match.url_name == 'edit' %}text-dark{% endif %}">Изменить профиль</span>
                        </span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'notification:notification' %}">
                        <span class="g-menu-item-content">
                            <span class="g-menu-item-title g-bold {% if request.resolver_match.url_name == 'notification' %}text-dark{% endif %}">
                                Уведомления
                                {% if notification != 0 %}
                                    ({{ notification }}){% endif %}
                            </span>
                        </span>
                    </a>
                </li>

                {% if user.is_staff %}
                    <li>
                        <a href="{% url 'cabinet:moderation' %}">
                            <span class="g-menu-item-content">
                                <span class="g-menu-item-title g-bold">
                                    Модерация
                                    {% if score_article != 0 %}
                                        ({{ score_article }}){% endif %}</span>
                            </span>
                        </a>
                    </li>

                {% else %}

                    <li>
                        <a href="{% url 'cabinet:moderation' %}">
                            <span class="g-menu-item-content">
                                <span class="g-menu-item-title g-bold">
                                    На модерации
                                    {% if score_article != 0 %}
                                        ({{ score_article }}){% endif %}</span>
                            </span>
                        </a>
                    </li>

                {% endif %}

                {% if user.is_superuser %}
                    <li>
                        <a href="{% url 'admin:index' %}">
                            <span class="g-menu-item-content">
                                <span class="g-menu-item-title g-bold">Админка</span>
                            </span>
                        </a>
                    </li>
                {% endif %}

            </ul>
        </nav>
    </div>

</div>

cabinetapp/templates/cabinetapp/moderation.html
<div class="row">
    <div>
        <div class="row">

            {% if object.is_reviewing %}

                <div class="col-4 align-left">
                    <a href="{% url 'cabinet:moderation_check' pk=object.id result=1 %}">
                        <button class="btn btn-success" type="button">
                            Опубликовать
                        </button>
                    </a>
                </div>

                <div class="col-4 center">
                    <a href="{% url 'cabinet:moderation_check' pk=object.id result=2 %}">
                        <button class="btn btn-warning" type="button">
                            Отклонить
                        </button>
                    </a>
                </div>

                <div class="col-4 align-right">
                    <a href="{% url 'cabinet:delete_article' pk=object.id %}">
                        <button class="btn btn-danger" type="button">
                            Удалить
                        </button>
                    </a>
                </div>

            {% elif object.is_published %}

                <div class="col-6 align-left">
                    <a href="{% url 'cabinet:moderation_check' pk=object.id result=2 %}">
                        <button class="btn btn-warning" type="button">
                            Снять с публикации
                        </button>
                    </a>
                </div>

                <div class="col-6 align-right">
                    <a href="{% url 'cabinet:delete_article' pk=object.id %}">
                        <button class="btn btn-danger" type="button">
                            Удалить
                        </button>
                    </a>
                </div>

            {% endif %}

        </div>

    </div>
</div>

cabinetapp/templates/cabinetapp/new_article.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
    {% if request.resolver_match.url_name == 'edit_draft' %}
        <h1 class="center">Редактирование черновика статьи</h1>
    {% elif request.resolver_match.url_name == 'new_article' %}
        <h1 class="center">Создание новой статьи</h1>
    {% endif %}
    <div class="row">

        <div class="col-1"></div>

        <div class="col-10 g-bold">

            {% if request.resolver_match.url_name == 'new_article' %}
                <form action="{% url 'cabinet:new_article' %}" method="post">
            {% else %}
                <form action="{% url 'cabinet:edit_draft' article.id %}"
                      method="post">
            {% endif %}
            {% csrf_token %}
            <div class="row">

                <div class="col-12">
                    <small>Название статьи</small>
                    {{ form.title }}
                </div>

                <div class="col-12">
                    <small>Статья</small>
                    {{ form.content }}
                </div>

                <div class="col-6">
                    <small>Раздел</small>
                    {{ form.sections }}
                </div>

                <div class="col-6">
                    <small>Тэги</small>
                    {{ form.tags }}
                </div>

            </div>


            <div class="row">
                {% if request.resolver_match.url_name == 'new_article' %}

                    <div class="col-4 center">
                        <button class="btn btn-success" type="submit"
                                value="save" name="save">Опубликовать
                        </button>
                    </div>

                    <div class="col-4 center">
                        <button class="btn btn-danger" type="submit"
                                value="draft" name="draft">В черновик
                        </button>
                    </div>

                    <div class="col-4 center">
                        <button class="btn btn-inverse">
                            <a class="" href="#" onclick="history.back();">
                                Отмена
                            </a>
                        </button>
                    </div>

                {% elif request.resolver_match.url_name == 'edit_draft' and article_published == None %}

                    {% if user.banned %}
                        <div class="col-4 center">
                            <span class="btn btn-danger">
                                Опубликовать
                            </span>
                        </div>
                    {% else %}
                        <div class="col-4 center">
                            <button class="btn btn-success" type="submit"
                                    value="save" name="save">Опубликовать
                            </button>
                        </div>
                    {% endif %}

                    <div class="col-4 center">
                        <button class="btn btn-danger" type="submit"
                                value="draft" name="draft">Сохранить
                        </button>
                    </div>

                    <div class="col-4 center">
                        <button class="btn btn-inverse">
                            <a class="" href="#" onclick="history.back();">
                                Отмена
                            </a>
                        </button>
                    </div>

                {% elif request.resolver_match.url_name == 'edit_draft' and article_published %}

                    <div class="col-6 center">
                        <button class="btn btn-danger" type="submit"
                                value="draft" name="draft">В черновик
                        </button>
                    </div>

                    <div class="col-6 center">
                        <button class="btn btn-inverse">
                            <a class="" href="#" onclick="history.back();">
                                Отмена
                            </a>
                        </button>
                    </div>

                {% endif %}
            </div>

            </form>
        </div>
    </div>

{% endblock %}

{% block menu %}
    {% include 'mainapp/inc_main_menu.html' %}
{% endblock %}